Refactored dmenu_tasker to use taskers delete flag

diff --git a/tasker b/tasker
--- a/tasker
+++ b/tasker
@@ -21,22 +21,23 @@ read_tasks() {
 
 # Print help menu
 Help() {
-   echo "Tasker: Create and list tasks"
-   echo
-   echo "Syntax: tasker [-l|h] [-n \"name\"] [-c \"content\"]"
-   echo "options:"
-   echo "l               List tasks"
-   echo "h               Print this Help."
-   echo "n \"name\"        Name of new task."
-   echo "c \"content\"     Content for new task."
-   echo
-   echo "Usage:"
-   echo
-   echo "   -l can be piped into dmenu."
-   echo "   Both Name AND Content are required to create a new task. "
+    echo "Tasker: Create and list tasks"
+    echo
+    echo "Syntax: tasker [-l|h] [-t \"title\"] [-c \"content\"] [-d \"delete\"]"
+    echo "options:"
+    echo "l               List tasks"
+    echo "d               Delete a task."
+    echo "t \"title\"       Title/Name of new task."
+    echo "c \"content\"     Content for new task."
+    echo "h               Print this Help."
+    echo
+    echo "Usage:"
+    echo
+    echo "   -l can be piped into stdin. -d can be piped from stdin"
+    echo "   Both Title AND Content are required to create a new task. "
 }
 
-while getopts :lt:c:h:nd option; do
+while getopts :hlt:c:n:d option; do
     case $option in
         n)
             if [ -d "$HOME/.tasker" ]; then
@@ -50,6 +51,7 @@ while getopts :lt:c:h:nd option; do
             exit ;;
         d)
             read_tasks
+            fi
             echo "Delete Which? (Task Name):"
             read -p "Select Name: " i
             sed -i "/${i},*/d" $INPUT
@@ -76,12 +78,12 @@ done
 # Check if name and content exist
 if [ -z ${TITLE+x} ]; then 
     echo "Name is required to add a task.";
-    exit
+    exit 1
 fi
 
 if [ -z ${CONTENT+x} ]; then 
     echo "Content is required to add a task.";
-    exit
+    exit 1
 fi
 
 # Create new task
